version: "3.8"
services:
  discovery:
    build: ./eurekaserver1
    ports:
      - 8761:8761
    image: eurekaserver1

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: formationMicroService
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d  

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/db

  app:
    image: node
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - discovery
    environment:
      - MONGO_URI=mongodb://mongo:27017/test
      - EUREKA_SERVER_URL=http://discovery:8761/eureka/

  candidat:
    build: ./candidat1
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - 8081:8081
    image: candidate1
    depends_on:
      - discovery


  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8180:8080
    depends_on:
      - discovery

  formation:
    build: ./formation
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.datasource.url=jdbc:mysql://db:3306/formationMicroService?useUnicode=true&allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=spring
      - spring.datasource.password=spring
    ports:
      - 8088:8088
    image: formation
    depends_on:
      - discovery
      - db
      - keycloak
  
  test:
    build: ./test_ms
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.datasource.url=jdbc:mysql://db:3306/formationMicroService?useUnicode=true&allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=spring
      - spring.datasource.password=spring
    ports:
      - 8090:8090
    image: test
    depends_on:
      - discovery
      - db
      - keycloak

  offre:
    build: ./offrems
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.datasource.url=jdbc:mysql://db:3306/formationMicroService?useUnicode=true&allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=spring
      - spring.datasource.password=spring
    ports:
      - 8091:8091
    image: offre
    depends_on:
      - discovery
      - db
      - keycloak

    
  contrat:
    build: ./projetmicroservicecontrat
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.datasource.url=jdbc:mysql://db:3306/formationMicroService?useUnicode=true&allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=spring
      - spring.datasource.password=spring
    ports:
      - 8092:8092
    image: contrat
    depends_on:
      - discovery
      - db
      - keycloak
      
    
  portfolio:
    build: ./microserviceProject-yassine
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.datasource.url=jdbc:mysql://db:3306/formationMicroService?useUnicode=true&allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=spring
      - spring.datasource.password=spring
    ports:
      - 8093:8093
    image: portfolio
    depends_on:
      - discovery
      - db
      - keycloak
      
  entretien:
    build: ./microserviceProject-Skander2
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.datasource.url=jdbc:mysql://db:3306/formationMicroService?useUnicode=true&allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=spring
      - spring.datasource.password=spring
    ports:
      - 8094:8094
    image: entretien
    depends_on:
      - discovery
      - db
      - keycloak

  apigateway:
      build: ./apigateway
      environment:
        - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      ports:
        - 8082:8082
      image: apigateway
      depends_on:
        - discovery